export type ProviderOptionProvider = "web" | "executable";
export type ProviderOptionType = "text" | "number" | "boolean" | "select" | "secret";
export type ProviderOptionValue = string | number | boolean;

export interface ProviderOptionChoice {
  value: string;
  label: string;
}

export interface ProviderOptionDefinition {
  id: string;
  provider: ProviderOptionProvider;
  group: string;
  type: ProviderOptionType;
  label: string;
  defaultValue: ProviderOptionValue;
  tooltip: string;
  source: string;
  choices?: ProviderOptionChoice[];
  min?: number;
  max?: number;
  step?: number;
  locked?: boolean;
  secret?: boolean;
  requiresReload?: boolean;
}

const backendChoices: ProviderOptionChoice[] = [
  { value: "auto", label: "Auto" },
  { value: "cpu", label: "CPU" },
  { value: "gpu", label: "GPU" },
  { value: "npu", label: "NPU" },
  { value: "cuda", label: "CUDA probe-only" },
];

const mediaBackendChoices: ProviderOptionChoice[] = [
  { value: "auto", label: "Auto" },
  { value: "cpu", label: "CPU" },
  { value: "gpu", label: "GPU" },
];

const webBackendChoices: ProviderOptionChoice[] = [
  { value: "UNSPECIFIED", label: "Unspecified" },
  { value: "CPU", label: "CPU" },
  { value: "GPU", label: "GPU" },
  { value: "NPU", label: "NPU" },
];

const samplerTypeChoices: ProviderOptionChoice[] = [
  { value: "TYPE_UNSPECIFIED", label: "Unspecified" },
  { value: "TOP_K", label: "Top K" },
  { value: "TOP_P", label: "Top P" },
  { value: "GREEDY", label: "Greedy" },
];

const speculativeDecodingChoices: ProviderOptionChoice[] = [
  { value: "auto", label: "Auto" },
  { value: "true", label: "True" },
  { value: "false", label: "False" },
];

const cacheChoices: ProviderOptionChoice[] = [
  { value: "disk", label: "Disk" },
  { value: "memory", label: "Memory" },
  { value: "no", label: "No cache" },
];

const webEngineSource =
  "demo/node_modules/@litert-lm/core/dist/engine_settings.d.ts";
const webSessionSource =
  "demo/node_modules/@litert-lm/core/dist/session_config.d.ts";
const webConversationSource =
  "demo/node_modules/@litert-lm/core/dist/conversation_config.d.ts";
const wasmBindingSource =
  "demo/node_modules/@litert-lm/core/dist/wasm_binding_types.d.ts";
const executableProviderSource = "demo/src/lib/providers/executableProvider.ts";
const endpointSource = "demo/src/lib/providers/endpoint.ts";
const sidecarSource = "native/sidecar/cmd/litert-sidecar/main.go";
const litertSource = "native/sidecar/internal/litert/litert.go";
const nativeDocsSource = "docs/litert-lm-native-provider.md";

export const providerOptionMetadata: ProviderOptionDefinition[] = [
  {
    id: "wasmPath",
    provider: "web",
    group: "Engine",
    type: "text",
    label: "WASM path",
    defaultValue: "/vendor/litert-lm/core/wasm",
    tooltip: "LiteRT-LM WASM asset directory loaded before creating the web engine.",
    source: "demo/src/lib/modelConfig.ts and demo/src/App.tsx",
    requiresReload: true,
  },
  {
    id: "engineBackend",
    provider: "web",
    group: "Engine",
    type: "select",
    label: "Engine backend",
    defaultValue: "GPU",
    tooltip: "Backend enum passed to LiteRT-LM engine creation when wired.",
    source: wasmBindingSource,
    choices: webBackendChoices,
    requiresReload: true,
  },
  {
    id: "maxNumTokens",
    provider: "web",
    group: "Engine",
    type: "number",
    label: "Context tokens",
    defaultValue: 8192,
    tooltip: "Maximum token capacity for the main LiteRT-LM executor.",
    source: webEngineSource,
    min: 256,
    max: 32768,
    step: 256,
    requiresReload: true,
  },
  {
    id: "maxOutputTokens",
    provider: "web",
    group: "Sampling",
    type: "number",
    label: "Output tokens",
    defaultValue: 1024,
    tooltip: "Maximum tokens generated for a web session response.",
    source: webSessionSource,
    min: 1,
    max: 8192,
    step: 1,
  },
  {
    id: "samplerBackend",
    provider: "web",
    group: "Sampling",
    type: "select",
    label: "Sampler backend",
    defaultValue: "UNSPECIFIED",
    tooltip: "Backend enum used for LiteRT-LM sampler execution.",
    source: webSessionSource,
    choices: webBackendChoices,
  },
  {
    id: "samplerType",
    provider: "web",
    group: "Sampling",
    type: "select",
    label: "Sampler",
    defaultValue: "TOP_K",
    tooltip: "LiteRT-LM sampler type for next-token selection.",
    source: `${webSessionSource}; ${wasmBindingSource}`,
    choices: samplerTypeChoices,
  },
  {
    id: "topK",
    provider: "web",
    group: "Sampling",
    type: "number",
    label: "Top K",
    defaultValue: 40,
    tooltip: "Limits sampling to the top K candidate tokens.",
    source: webSessionSource,
    min: 1,
    max: 1024,
    step: 1,
  },
  {
    id: "topP",
    provider: "web",
    group: "Sampling",
    type: "number",
    label: "Top P",
    defaultValue: 0.95,
    tooltip: "Nucleus sampling probability threshold.",
    source: webSessionSource,
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    id: "temperature",
    provider: "web",
    group: "Sampling",
    type: "number",
    label: "Temperature",
    defaultValue: 0.7,
    tooltip: "Sampling temperature; lower values make output more deterministic.",
    source: `${webSessionSource}; demo/src/App.tsx`,
    min: 0,
    max: 2,
    step: 0.05,
  },
  {
    id: "seed",
    provider: "web",
    group: "Sampling",
    type: "number",
    label: "Seed",
    defaultValue: 0,
    tooltip: "Sampler seed. Zero keeps the default runtime behavior.",
    source: webSessionSource,
    min: 0,
    max: 4294967295,
    step: 1,
  },
  {
    id: "stopTokenIds",
    provider: "web",
    group: "Sampling",
    type: "text",
    label: "Stop token IDs",
    defaultValue: "",
    tooltip: "Optional token ID sequences that stop web session generation.",
    source: webSessionSource,
  },
  {
    id: "startTokenId",
    provider: "web",
    group: "Sampling",
    type: "number",
    label: "Start token ID",
    defaultValue: 0,
    tooltip: "Optional positive start token ID passed to the web session.",
    source: webSessionSource,
    min: 0,
    step: 1,
  },
  {
    id: "numOutputCandidates",
    provider: "web",
    group: "Sampling",
    type: "number",
    label: "Output candidates",
    defaultValue: 0,
    tooltip: "Optional positive number of output candidates generated by the web session.",
    source: webSessionSource,
    min: 0,
    step: 1,
  },
  {
    id: "systemPrompt",
    provider: "web",
    group: "Conversation",
    type: "text",
    label: "System prompt",
    defaultValue: "You are a concise local assistant running through LiteRT-LM.",
    tooltip: "System preface message used to initialize the conversation.",
    source: webConversationSource,
  },
  {
    id: "enableConstrainedDecoding",
    provider: "web",
    group: "Conversation",
    type: "boolean",
    label: "Constrained decoding",
    defaultValue: false,
    tooltip: "Enables LiteRT-LM constrained decoding for compatible sessions.",
    source: webConversationSource,
  },
  {
    id: "prefillPrefaceOnInit",
    provider: "web",
    group: "Conversation",
    type: "boolean",
    label: "Prefill preface",
    defaultValue: false,
    tooltip: "Prefills configured preface content when a conversation starts.",
    source: webConversationSource,
  },
  {
    id: "filterChannelContentFromKvCache",
    provider: "web",
    group: "Conversation",
    type: "boolean",
    label: "Filter channel KV",
    defaultValue: false,
    tooltip: "Filters channel content from the KV cache when supported.",
    source: webConversationSource,
  },
  {
    id: "applyPromptTemplateInSession",
    provider: "web",
    group: "Conversation",
    type: "boolean",
    label: "Session template",
    defaultValue: true,
    tooltip: "Applies the model prompt template inside the LiteRT-LM session.",
    source: webSessionSource,
  },
  {
    id: "useExternalSampler",
    provider: "web",
    group: "Conversation",
    type: "boolean",
    label: "External sampler",
    defaultValue: false,
    tooltip: "Uses an external sampler hook instead of the built-in sampler.",
    source: webSessionSource,
  },
  {
    id: "visionModalityEnabled",
    provider: "web",
    group: "Web modalities",
    type: "boolean",
    label: "Vision modality",
    defaultValue: false,
    tooltip: "Visible but locked off because this web UI path is currently text-only.",
    source: `${webSessionSource}; ${nativeDocsSource}`,
    locked: true,
  },
  {
    id: "audioModalityEnabled",
    provider: "web",
    group: "Web modalities",
    type: "boolean",
    label: "Audio modality",
    defaultValue: false,
    tooltip: "Visible but locked off because this web UI path is currently text-only.",
    source: `${webSessionSource}; ${nativeDocsSource}`,
    locked: true,
  },
  {
    id: "endpoint",
    provider: "executable",
    group: "Connection/request",
    type: "text",
    label: "Endpoint",
    defaultValue: "http://127.0.0.1:9379/v1",
    tooltip: "OpenAI-compatible sidecar endpoint used by executable requests.",
    source: endpointSource,
  },
  {
    id: "modelId",
    provider: "executable",
    group: "Connection/request",
    type: "text",
    label: "Model ID",
    defaultValue: "gemma4-e2b",
    tooltip: "Request model ID and sidecar registry ID used for LiteRT-LM import/serve.",
    source: `${executableProviderSource}; ${sidecarSource}; ${litertSource}`,
  },
  {
    id: "backend",
    provider: "executable",
    group: "Connection/request",
    type: "select",
    label: "Backend",
    defaultValue: "auto",
    tooltip: "Native backend suffix for LiteRT-LM model selection; CUDA is probe-only.",
    source: `${executableProviderSource}; ${nativeDocsSource}`,
    choices: backendChoices,
  },
  {
    id: "maxNumTokens",
    provider: "executable",
    group: "Connection/request",
    type: "number",
    label: "Context tokens",
    defaultValue: 8192,
    tooltip: "Token suffix sent with concrete executable backend model IDs.",
    source: executableProviderSource,
    min: 256,
    max: 32768,
    step: 256,
  },
  {
    id: "maxTokens",
    provider: "executable",
    group: "Connection/request",
    type: "number",
    label: "Output tokens",
    defaultValue: 1024,
    tooltip: "OpenAI-compatible max_tokens value for executable text chat responses.",
    source: executableProviderSource,
    min: 1,
    max: 8192,
    step: 1,
  },
  {
    id: "stream",
    provider: "executable",
    group: "Connection/request",
    type: "boolean",
    label: "Stream",
    defaultValue: true,
    tooltip: "Executable text requests stream OpenAI-compatible server-sent events.",
    source: executableProviderSource,
    locked: true,
  },
  {
    id: "addr",
    provider: "executable",
    group: "Sidecar",
    type: "text",
    label: "Sidecar addr",
    defaultValue: "127.0.0.1:9379",
    tooltip: "Sidecar listen address passed with -addr.",
    source: sidecarSource,
    requiresReload: true,
  },
  {
    id: "upstream",
    provider: "executable",
    group: "Sidecar",
    type: "text",
    label: "Upstream",
    defaultValue: "http://127.0.0.1:9381",
    tooltip: "LiteRT-LM server URL proxied by the sidecar.",
    source: sidecarSource,
    requiresReload: true,
  },
  {
    id: "launchRuntime",
    provider: "executable",
    group: "Sidecar",
    type: "boolean",
    label: "Launch runtime",
    defaultValue: true,
    tooltip: "Starts and manages a litert-lm serve child process.",
    source: sidecarSource,
    requiresReload: true,
  },
  {
    id: "runtimeExe",
    provider: "executable",
    group: "Sidecar",
    type: "text",
    label: "Runtime exe",
    defaultValue: "",
    tooltip: "Path to litert-lm; blank searches PATH and bundled locations.",
    source: `${sidecarSource}; ${litertSource}`,
    requiresReload: true,
  },
  {
    id: "runtimeHost",
    provider: "executable",
    group: "Sidecar",
    type: "text",
    label: "Runtime host",
    defaultValue: "127.0.0.1",
    tooltip: "Host passed to litert-lm serve.",
    source: `${sidecarSource}; ${litertSource}`,
    requiresReload: true,
  },
  {
    id: "runtimePort",
    provider: "executable",
    group: "Sidecar",
    type: "number",
    label: "Runtime port",
    defaultValue: 9381,
    tooltip: "Port passed to litert-lm serve.",
    source: `${sidecarSource}; ${litertSource}`,
    min: 1,
    max: 65535,
    step: 1,
    requiresReload: true,
  },
  {
    id: "modelFile",
    provider: "executable",
    group: "Sidecar",
    type: "text",
    label: "Model file",
    defaultValue: "demo/models/gemma-4-E2B-it.litertlm",
    tooltip: "Local .litertlm model file imported before serving when needed.",
    source: `${sidecarSource}; ${litertSource}; ${nativeDocsSource}`,
    requiresReload: true,
  },
  {
    id: "importModel",
    provider: "executable",
    group: "Sidecar",
    type: "boolean",
    label: "Import model",
    defaultValue: true,
    tooltip: "Imports the model file into the LiteRT-LM registry when missing.",
    source: sidecarSource,
    requiresReload: true,
  },
  {
    id: "runtimeVerbose",
    provider: "executable",
    group: "Sidecar",
    type: "boolean",
    label: "Runtime verbose",
    defaultValue: false,
    tooltip: "Passes --verbose to litert-lm serve.",
    source: sidecarSource,
    requiresReload: true,
  },
  {
    id: "preset",
    provider: "executable",
    group: "Run/multimodal",
    type: "text",
    label: "Preset",
    defaultValue: "",
    tooltip: "Optional litert-lm run preset name when the local CLI supports presets.",
    source: "litert-lm run help established in local planning output",
  },
  {
    id: "noTemplate",
    provider: "executable",
    group: "Run/multimodal",
    type: "boolean",
    label: "No template",
    defaultValue: false,
    tooltip: "Disables prompt templating for litert-lm run when supported.",
    source: "litert-lm run help established in local planning output",
  },
  {
    id: "filterChannelContentFromKvCache",
    provider: "executable",
    group: "Run/multimodal",
    type: "boolean",
    label: "Filter channel KV",
    defaultValue: false,
    tooltip: "Filters channel content from KV cache for native runs when supported.",
    source: "litert-lm run help established in local planning output",
  },
  {
    id: "visionBackend",
    provider: "executable",
    group: "Run/multimodal",
    type: "select",
    label: "Vision backend",
    defaultValue: "auto",
    tooltip: "Backend for image attachments in native multimodal runs.",
    source: `${nativeDocsSource}; ${litertSource}`,
    choices: mediaBackendChoices,
  },
  {
    id: "audioBackend",
    provider: "executable",
    group: "Run/multimodal",
    type: "select",
    label: "Audio backend",
    defaultValue: "auto",
    tooltip: "Backend for audio attachments in native multimodal runs.",
    source: `${nativeDocsSource}; ${litertSource}`,
    choices: mediaBackendChoices,
  },
  {
    id: "topK",
    provider: "executable",
    group: "Run/multimodal",
    type: "number",
    label: "Top K",
    defaultValue: 40,
    tooltip: "Native run top-K sampling value when the CLI flag is available.",
    source: "litert-lm run help established in local planning output",
    min: 1,
    max: 1024,
    step: 1,
  },
  {
    id: "topP",
    provider: "executable",
    group: "Run/multimodal",
    type: "number",
    label: "Top P",
    defaultValue: 0.95,
    tooltip: "Native run nucleus sampling threshold when the CLI flag is available.",
    source: "litert-lm run help established in local planning output",
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    id: "temperature",
    provider: "executable",
    group: "Run/multimodal",
    type: "number",
    label: "Temperature",
    defaultValue: 0.7,
    tooltip: "Native run sampling temperature when the CLI flag is available.",
    source: "litert-lm run help established in local planning output",
    min: 0,
    max: 2,
    step: 0.05,
  },
  {
    id: "seed",
    provider: "executable",
    group: "Run/multimodal",
    type: "number",
    label: "Seed",
    defaultValue: 0,
    tooltip: "Native run sampler seed; zero keeps default runtime behavior.",
    source: "litert-lm run help established in local planning output",
    min: 0,
    max: 4294967295,
    step: 1,
  },
  {
    id: "enableSpeculativeDecoding",
    provider: "executable",
    group: "Run/multimodal",
    type: "select",
    label: "Speculative decoding",
    defaultValue: "auto",
    tooltip: "Native run speculative decoding policy: auto, true, or false.",
    source: "litert-lm run help established in local planning output",
    choices: speculativeDecodingChoices,
  },
  {
    id: "cache",
    provider: "executable",
    group: "Run/multimodal",
    type: "select",
    label: "Cache",
    defaultValue: "disk",
    tooltip: "Native run cache behavior: disk, memory, or no cache.",
    source: "litert-lm run help established in local planning output",
    choices: cacheChoices,
  },
  {
    id: "verbose",
    provider: "executable",
    group: "Run/multimodal",
    type: "boolean",
    label: "Verbose",
    defaultValue: false,
    tooltip: "Enables verbose native run output when supported.",
    source: "litert-lm run help established in local planning output",
  },
  {
    id: "fromHuggingFaceRepo",
    provider: "executable",
    group: "Run/multimodal",
    type: "text",
    label: "HF repo",
    defaultValue: "",
    tooltip: "Optional Hugging Face repository source for import/run flows.",
    source: "litert-lm import help established in local planning output",
  },
  {
    id: "huggingfaceToken",
    provider: "executable",
    group: "Run/multimodal",
    type: "secret",
    label: "HF token",
    defaultValue: "",
    tooltip: "Sent only to the local sidecar; the sidecar injects it as HF_TOKEN and HUGGING_FACE_HUB_TOKEN instead of CLI args.",
    source: "litert-lm import help established in local planning output",
    secret: true,
  },
];

export function getProviderOptionMetadata(
  provider: ProviderOptionProvider,
): ProviderOptionDefinition[] {
  return providerOptionMetadata.filter((option) => option.provider === provider);
}

export function getProviderOptionDefinition(
  provider: ProviderOptionProvider,
  id: string,
): ProviderOptionDefinition | undefined {
  return providerOptionMetadata.find(
    (option) => option.provider === provider && option.id === id,
  );
}
